name: 'pitch_analysis'
config-version: 2
version: '1.0.0'

profile: 'pitch_analysis_dw'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: [target, dbt_packages]

models:
  pitch_analysis:
    example:
seeds:
  pitch_analysis:
    +tags: ["staging"]
    +meta:
      layer: staging
    +tblproperties:
      layer: staging